#pragma once
#include<string>
using namespace std;
void procedur();
void constState();
void constDef();
void charDef();
string intDef();
void unIntDef();
void varState();
void varDef();
string varInitial(string name,int dimension, int line, int row, string type);
void compState();
void senList();
bool sentence();
void switchState();
void defaultState();
void caseList(string type);
void caseSen(string type);
void returnState();
void printState();
void readState();
void assignState();
void looper();
void ifState();
void stepLen();
void condition();
string expression();
string iterm();
string factor();
int FunCall();
void valueList(string name,int namePosition);
void paraList();
void func();
void voidfunc();
void mainFunc();
void output();
bool nameDupError(string name);
int getName(string s, string linenum);
int callName();
void errorPut();
void errorTest();